export const categories = ['Áo', 'Đầm & Váy', 'Áo Khoác', 'Giày', 'Phụ Kiện'];

export const products = [
  {
    id: 1,
    title: 'Áo thun cotton basic',
    price: 290000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.6,
  },
  {
    id: 2,
    title: 'Túi tote vải canvas',
    price: 180000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.8,
  },
  {
    id: 3,
    title: 'Áo khoác gió nhẹ',
    price: 620000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo Khoác',
    rating: 4.7,
  },
  {
    id: 4,
    title: 'Áo croptop gân tăm',
    price: 230000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.5,
  },
  {
    id: 5,
    title: 'Áo sơ mi linen tay dài',
    price: 520000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.8,
  },
  {
    id: 6,
    title: 'Áo polo cổ bẻ',
    price: 350000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.4,
  },
  {
    id: 7,
    title: 'Áo khoác denim',
    price: 790000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo Khoác',
    rating: 4.9,
  },
  {
    id: 8,
    title: 'Túi đeo chéo mini',
    price: 320000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.3,
  },
  {
    id: 9,
    title: 'Áo thun kẻ ngang',
    price: 260000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.6,
  },
  {
    id: 10,
    title: 'Túi du lịch cuối tuần',
    price: 650000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.7,
  },
  {
    id: 11,
    title: 'Áo thun oversize',
    price: 310000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.7,
  },
  {
    id: 12,
    title: 'Đầm linen dáng suông',
    price: 460000,
    thumbnail: './assets/dress.svg',
    category: 'Đầm & Váy',
    rating: 4.6,
  },
  {
    id: 13,
    title: 'Áo len cổ tròn',
    price: 580000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.8,
  },
  {
    id: 14,
    title: 'Áo cardigan mỏng',
    price: 540000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo Khoác',
    rating: 4.5,
  },
  {
    id: 15,
    title: 'Áo khoác bomber',
    price: 850000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo Khoác',
    rating: 4.8,
  },
  {
    id: 16,
    title: 'Túi đeo vai da mềm',
    price: 490000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.6,
  },
  {
    id: 17,
    title: 'Chân váy chữ A',
    price: 190000,
    thumbnail: './assets/dress.svg',
    category: 'Đầm & Váy',
    rating: 4.4,
  },
  {
    id: 18,
    title: 'Áo blouse tay phồng',
    price: 420000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.7,
  },
  {
    id: 19,
    title: 'Áo hoodie nỉ',
    price: 590000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo Khoác',
    rating: 4.9,
  },
  {
    id: 20,
    title: 'Balo canvas hằng ngày',
    price: 450000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.7,
  },
  {
    id: 21,
    title: 'Đầm hoa nhí',
    price: 250000,
    thumbnail: './assets/dress.svg',
    category: 'Đầm & Váy',
    rating: 4.5,
  },
  {
    id: 22,
    title: 'Giày sneaker trắng',
    price: 480000,
    thumbnail: './assets/shoe.svg',
    category: 'Giày',
    rating: 4.6,
  },
  {
    id: 23,
    title: 'Áo khoác kaki',
    price: 720000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo Khoác',
    rating: 4.8,
  },
  {
    id: 24,
    title: 'Túi tote có khóa kéo',
    price: 220000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.5,
  },
  {
    id: 25,
    title: 'Giày loafer da mềm',
    price: 470000,
    thumbnail: './assets/shoe.svg',
    category: 'Giày',
    rating: 4.7,
  },
  {
    id: 26,
    title: 'Áo len cổ lọ',
    price: 610000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.8,
  },
  {
    id: 27,
    title: 'Áo khoác chống nắng',
    price: 390000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo Khoác',
    rating: 4.6,
  },
  {
    id: 28,
    title: 'Túi đeo chéo thể thao',
    price: 280000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.4,
  },
  {
    id: 29,
    title: 'Giày sandal quai ngang',
    price: 330000,
    thumbnail: './assets/shoe.svg',
    category: 'Giày',
    rating: 4.6,
  },
  {
    id: 30,
    title: 'Túi xách công sở',
    price: 690000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ Kiện',
    rating: 4.9,
  },
];
