export const products = [
  {
    id: 1,
    title: 'Áo thun cotton basic',
    price: 290000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.6,
  },
  {
    id: 2,
    title: 'Túi tote vải canvas',
    price: 180000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ kiện',
    rating: 4.8,
  },
  {
    id: 3,
    title: 'Áo khoác gió nhẹ',
    price: 620000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo khoác',
    rating: 4.7,
  },
  {
    id: 4,
    title: 'Áo croptop gân tăm',
    price: 230000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.5,
  },
  {
    id: 5,
    title: 'Áo sơ mi linen tay dài',
    price: 520000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.8,
  },
  {
    id: 6,
    title: 'Áo polo cổ bẻ',
    price: 350000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.4,
  },
  {
    id: 7,
    title: 'Áo khoác denim',
    price: 790000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo khoác',
    rating: 4.9,
  },
  {
    id: 8,
    title: 'Túi đeo chéo mini',
    price: 320000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ kiện',
    rating: 4.3,
  },
  {
    id: 9,
    title: 'Áo thun kẻ ngang',
    price: 260000,
    thumbnail: './assets/shirt.svg',
    category: 'Áo',
    rating: 4.6,
  },
  {
    id: 10,
    title: 'Túi du lịch cuối tuần',
    price: 650000,
    thumbnail: './assets/bag.svg',
    category: 'Phụ kiện',
    rating: 4.7,
  },
];
